## Deliverable 3. Create a Travel Itinerary Map.

In [1]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps

# Import API key
from config import g_key

# Configure gmaps
gmaps.configure(api_key=g_key)

In [2]:
# 1. Read the WeatherPy_vacation.csv into a DataFrame.
vacation_df = pd.read_csv("../Vacation_Search/WeatherPy_vacation.csv")
#vacation_df['Lat'] = vacation_df['Lat'].apply('{:.2f}'.format)
#vacation_df['Lng'] = vacation_df['Lng'].apply('{:.2f}'.format)
vacation_df

,City_ID,City,Country,Max Temp,WeatherDesc,Lat,Lng,HotelName
0,0,Kavieng,PG,85.12,overcast clouds,-2.5744,150.7967,Nusa Island Retreat
1,1,Daoukro,CI,74.25,overcast clouds,7.0591,-3.9631,Komenan brou roseline
2,2,Ponta Do Sol,PT,66.06,overcast clouds,32.6667,-17.1000,Hotel do Campo
3,4,Faanui,PF,81.70,overcast clouds,-16.4833,-151.7500,Bora-Bora Pearl Beach Resort & Spa
4,5,Cidreira,BR,70.57,overcast clouds,-30.1811,-50.2056,Hotel Castelo
...,...,...,...,...,...,...,...,...
259,407,Coatepec,MX,51.31,overcast clouds,19.4500,-96.9667,Hotel Posada Coatepec
260,408,Gambela,ET,80.85,overcast clouds,8.2500,34.5833,Solomon Debebe Hotel
261,409,Bethlehem,BR,78.84,clear sky,-1.4558,-48.5044,Mercure Belém Boulevard
262,412,Te Anau,NZ,64.15,clear sky,-45.4167,167.7167,Kingsgate Hotel Te Anau
263,413,Geraldton,AU,75.61,broken clouds,-28.7667,114.6000,Broadwater Mariner Resort

In [3]:
# 2. Using the template add the city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """
<dl>
<dt>CityName</dt><dd>{City}</dd>
<dt>CountryCode</dt><dd>{Country}</dd>
<dt>WeatherDesc</dt><dd>{WeatherDesc}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""

# 3a. Get the data from each row and add it to the formatting template and store the data in a list.
vacation_info = [info_box_template.format(**row) for index, row in vacation_df.iterrows()]

# 3b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = vacation_df[["Lat", "Lng"]]

In [4]:
locations

         Lat       Lng
0    -2.5744  150.7967
1     7.0591   -3.9631
2    32.6667  -17.1000
3   -16.4833 -151.7500
4   -30.1811  -50.2056
..       ...       ...
259  19.4500  -96.9667
260   8.2500   34.5833
261  -1.4558  -48.5044
262 -45.4167  167.7167
263 -28.7667  114.6000

[264 rows x 2 columns]

In [5]:
# 4a. Add a marker layer for each city to the map.

marker_layer = gmaps.marker_layer(locations, info_box_content=vacation_info)

fig = gmaps.figure()

fig.add_layer(marker_layer)

# 4b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))

In [6]:
# From the map above pick 4 cities and create a vacation itinerary route to travel between the four cities. 
# 5. Create DataFrames for each city by filtering the 'vacation_df' using the loc method. 
# Hint: The starting and ending city should be the same city.
itinerary_df = vacation_df[["HotelName","City", "Country", "Lat", "Lng", "WeatherDesc","Max Temp"]].copy()
itinerary_df['Lat'] = itinerary_df['Lat'].apply('{:.2f}'.format)
itinerary_df['Lng'] = itinerary_df['Lng'].apply('{:.2f}'.format)
vacation_start = itinerary_df.loc[vacation_df['City'] == "San Jose", ['Lat'] + ['Lng']]
vacation_end = itinerary_df.loc[vacation_df['City'] == "San Jose", ['Lat']+['Lng']]
vacation_stop1 = itinerary_df.loc[vacation_df['City'] == "Lompoc", ['Lat']+['Lng']]
vacation_stop2 = itinerary_df.loc[vacation_df['City'] == "Ridgecrest", ['Lat']+['Lng']] 
vacation_stop3 = itinerary_df.loc[vacation_df['City'] == "Saint George", ['Lat']+['Lng']] 
#print(vacation_start)
itinerary_df

,HotelName,City,Country,Lat,Lng,WeatherDesc,Max Temp
0,Nusa Island Retreat,Kavieng,PG,-2.57,150.80,overcast clouds,85.12
1,Komenan brou roseline,Daoukro,CI,7.06,-3.96,overcast clouds,74.25
2,Hotel do Campo,Ponta Do Sol,PT,32.67,-17.10,overcast clouds,66.06
3,Bora-Bora Pearl Beach Resort & Spa,Faanui,PF,-16.48,-151.75,overcast clouds,81.70
4,Hotel Castelo,Cidreira,BR,-30.18,-50.21,overcast clouds,70.57
...,...,...,...,...,...,...,...
259,Hotel Posada Coatepec,Coatepec,MX,19.45,-96.97,overcast clouds,51.31
260,Solomon Debebe Hotel,Gambela,ET,8.25,34.58,overcast clouds,80.85
261,Mercure Belém Boulevard,Bethlehem,BR,-1.46,-48.50,clear sky,78.84
262,Kingsgate Hotel Te Anau,Te Anau,NZ,-45.42,167.72,clear sky,64.15
263,Broadwater Mariner Resort,Geraldton,AU,-28.77,114.60,broken clouds,75.61

In [8]:
# 6. Get the latitude-longitude pairs as tuples from each city DataFrame using the to_numpy function and list indexing.
start = vacation_start
end = vacation_end
stop1 = vacation_stop1
stop2 = vacation_stop2
stop3 = vacation_stop3
#
start = (37.3394,-121.895)
end = (37.3394,-121.895)
stop1 = (34.6391,-120.4579)
stop2 = (35.6225,-117.6709)
stop3 = (37.3394,-121.895)
print(start)

(37.3394, -121.895)

In [9]:
# 7. Create a direction layer map using the start and end latitude-longitude pairs,
# and stop1, stop2, and stop3 as the waypoints. The travel_mode should be "DRIVING", "BICYCLING", or "WALKING".
import gmaps.datasets

fig = gmaps.figure()
start2end =\
    gmaps.directions_layer(start, end, waypoints=[stop1, stop2, stop3], 
                                 travel_mode='DRIVING')
fig.add_layer(start2end)
fig

Figure(layout=FigureLayout(height='420px'))

In [ ]:
# 8. To create a marker layer map between the four cities.
#  Combine the four city DataFrames into one DataFrame using the concat() function.
vacation_df = pd.concat([],ignore_index=True)
vacation_df

In [12]:
# 9 Using the template add city name, the country code, the weather description and maximum temperature for the city. 
info_box_template = """
<dl>
<dt>CityName</dt><dd>{City}</dd>
<dt>CountryCode</dt><dd>{Country}</dd>
<dt>WeatherDesc</dt><dd>{WeatherDesc}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""

# 10a Get the data from each row and add it to the formatting template and store the data in a list.
vacation_info = [info_box_template.format(**row) for index, row in itinerary_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = vacation_df[["Lat", "Lng"]]

In [13]:
# 11a. Add a marker layer for each city to the map.

marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)

fig = gmaps.figure()

fig.add_layer(marker_layer)

# 11b. Display the figure
fig

NameError: name 'hotel_info' is not defined